# Generated by Django 5.2.3 on 2025-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
