# Generated by Django 5.2.3 on 2025-06-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='recipient_name',
        ),
    ]
